[package]
name = "kdam"
version = "0.2.3"
edition = "2021"
description = "Ultimate console progress bar for Rust"
repository = "https://github.com/clitic/kdam"
documentation = "https://docs.rs/kdam"
categories = ["command-line-interface"]
keywords = [
	"cli",
	"progress",
	"progressbar",
	"pb",
]
license = "MIT"
readme = "README.md"
exclude = ["images"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
terminal_size = "0.2"

[workspace]

members = ["examples/file_download"]
