name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Tests # https://pyo3.rs/main/faq
      run: cargo test -p kdam -p kdam_derive --all-features
    - name: Build file_download example
      run: cargo build -p file_download
    - name: Build notebook example
      run: cargo build -p notebook
